
name: Deploy IoT Lambda

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Zip Lambda
        run: |
          cd iot-lambda-terraform/lambda
          zip ../lambda.zip handler.py

      - name: Terraform Init & Apply
        run: |
          cd iot-lambda-terraform
          terraform init
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
